### ISSUE TITLE
(*s3File).Open panics opening file with Content-Encoding: gzip

### ISSUE THREAD

**Issue by jcharum** [grailbio/base#15]
### Steps to reproduce

1. Create a file in S3, "s3://the-bucket/the-path".
2. Set `Content-Encoding: gzip` metadata on the file.
3. Call `(*s3File).Open` on that file. See the small example program below.

### Actual result
Get a panic that looks like:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8c5c05]

goroutine 6 [running]:
github.com/grailbio/base/file/s3file.newInfo(...)
	/home/ubuntu/code/base/file/s3file/s3file.go:726
github.com/grailbio/base/file/s3file.(*s3File).handleStat(0xc0000bd900, 0xbb7240, 0xc0000240e0, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000927e0)
	/home/ubuntu/code/base/file/s3file/s3file.go:761 +0x425
github.com/grailbio/base/file/s3file.(*s3File).handleRequests(0xc0000bd900)
	/home/ubuntu/code/base/file/s3file/s3file.go:657 +0x1a7
created by github.com/grailbio/base/file/s3file.(*s3Impl).internalOpen
	/home/ubuntu/code/base/file/s3file/s3file.go:457 +0x1f2
exit status 2
```

### Expected result
No panic and correct file information.

### Example program
```go
package main

import (
	"context"

	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/grailbio/base/file"
	"github.com/grailbio/base/file/s3file"
)

func init() {
	file.RegisterImplementation("s3", func() file.Implementation {
		return s3file.NewImplementation(
			s3file.NewDefaultProvider(session.Options{}),
			s3file.Options{},
		)
	})
}

func main() {
	const path = "s3://path/to/file/with/content-encoding/gzip"
	_, err := file.Open(context.Background(), path)
	if err != nil {
		panic(err)
	}
}
```

**Comment by jcharum** [comment]
See related issues:

- https://github.com/aws/aws-sdk-go/issues/1292
- https://github.com/aws/aws-sdk-go/issues/1837

**Comment by jcharum** [comment]
I think this happens because the gzip content encoding causes the object to be compressed on the wire. The SDK/transport decompresses transparently and clears the `ContentLength` on the output, presumably to avoid confusion between the compressed and uncompressed sizes. (The uncompressed size is not known until the full contents are read, so it can't replace it with the uncompressed size without lots of overhead).
